Bootstrap: localimage

From: ../images/dev_env.simg


%environment

    export CONTAINER_NAME=tools

%post

    apt-get update
    apt-get -y install dcmtk libgdcm-cil
    apt-get -y install imagemagick
    apt-get -y install httpie jq
    apt-get clean
