# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"
  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |vm|
    vm.memory = 8192
    config.vm.synced_folder "~/", "/home/vagrant", owner: "vagrant", group: "vagrant"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/site.yml"
    ansible.inventory_path = "provisioning/inventory"
    ansible.limit = "all"
  end
end
