[package]
name = "board_plugin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = []
debug = ["colored", "bevy-inspector-egui"]

[dependencies]
serde = "1.0"
rand = "0.8"
colored = { version = "2.0", optional = true }
bevy-inspector-egui = { version = "0.8", optional = true }

[dependencies.bevy]
version = "0.6"
default-features = false
features = ["render"]

[target.'cfg(target_arch = "wasm32")'.dependencies.getrandom]
version="0.2"
features = ["js"]