#!/usr/bin/env python3
import sys
from itertools import product


def solve(N: int, K: int):
    ret = 0
    for r, b in product(range(1, N+1), range(1, N+1)):
        rem = K - r - b
        if 0 < rem <= N:
            ret += 1
    print(ret)



# Generated by 2.13.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    K = int(next(tokens))  # type: int
    solve(N, K)

if __name__ == '__main__':
    main()
