project:
  type: website
  output-dir: docs

website:
  title: "lab_note"
  favicon: logo.png
  open-graph: true
  twitter-card: 
    site: "@ar90n"
  site-url: https://lab.ar90n.net
  image: logo.png
  description: my laboratory
  navbar:
    search: true
    right:
      - text: About
        file: about.qmd
      - text: Projects
        file: projects.qmd
      - icon: github
        href: https://github.com/ar90n
      - icon: twitter
        href: https://twitter.com/ar90n
      - icon: rss
        href: index.xml
  cookie-consent:
    type: express
    style: headline
    palette: dark
  google-analytics: "UA-90473091-1"

bibliography: references.bib
csl: acm-sig-proceedings.csl

execute:
  freeze: true
  cache: true

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



