version: '3'
services:
  purpur:
    image: 05jchambers/legendary-minecraft-purpur-geyser:latest
    ports:
    - "25565:25565"
    - "19132:19132/udp"
    - "19132:19132"
    volumes:
    - minecraft_world:/minecraft
volumes:
  minecraft_world: {}
