projects:
  app:
    schemaPath: src/schema.graphql
    extensions:
      endpoints:
        default: https://localhost:4000
  database:
    schemaPath: src/generated/prisma.graphql
    extensions:
      prisma: database/prisma.yml
