[[plugins]]
repo = 'scrooloose/syntastic'
hook_source = '''
    set statusline+=%#warningmsg#
    set statusline+=%{SyntasticStatuslineFlag()}
    set statusline+=%*

    let g:syntastic_fsharp_checkers=['syntax']

    let g:syntastic_always_populate_loc_list = 0
    let g:syntastic_auto_loc_list = 0
    let g:syntastic_check_on_open = 0
    let g:syntastic_check_on_wq = 0

    nmap <Leader>no :lopen<CR>      " open location window
    nmap <Leader>nc :lclose<CR>     " close location window
    nmap <Leader>n, :ll<CR>         " go to current error/warning
    nmap <Leader>nj :lnext<CR>      " next error/warning
    nmap <Leader>nk :lprev<CR>      " previous error/warning
'''
on_ft = ['fsharp']

[[plugins]]
repo = 'callmekohei/deoplete-fsharp'
build = 'bash ./install.bash'
on_ft = ['fsharp']

[[plugins]]
repo = 'SirVer/ultisnips'
hook_source = '''
    let g:UltiSnipsSnippetDirectories=["procon_snippets","mysnippets","dein/repos/github.com/honza/vim-snippets/UltiSnips"]
'''
on_ft = ['fsharp']
