#!/usr/bin/env python3
import sys


def solve(D: int, X: int, A: "List[int]", Q: int, S: "List[int]", T: "List[int]"):
    return


# Generated by 2.13.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    D = int(next(tokens))  # type: int
    X = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(D - 2 + 1)]  # type: "List[int]"
    Q = int(next(tokens))  # type: int
    S = [int()] * (Q)  # type: "List[int]"
    T = [int()] * (Q)  # type: "List[int]"
    for i in range(Q):
        S[i] = int(next(tokens))
        T[i] = int(next(tokens))
    solve(D, X, A, Q, S, T)

if __name__ == '__main__':
    main()
