FROM codercom/code-server:latest
	
RUN code-server --install-extension Shan.code-settings-sync && \
    code-server --install-extension vscodevim.vim && \
    code-server --install-extension GitHub.copilot && \
    code-server --install-extension ms-python.python && \
    code-server --install-extension python.vscode-pylance && \
    code-server --install-extension matklad.rust-analyzer && \
    code-server --install-extension ms-toolsai.jupyter && \
    code-server --install-extension yzhang.markdown-all-in-one && \
    code-server --install-extension hediet.vscode-drawio
