version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  go:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - UID=<UID>
        - GID=<GID>
    volumes:
      - ..:/workspace/go-url-shortener:cached
    depends_on:
      - redis
    tty: true
    stdin_open: true
