#!/usr/bin/env python3
import sys
import bisect

def solve(N: int, K: int, A: "List[int]"):
    A = sorted(A)

    ret = 0
    for i, a in enumerate(A):
        ret += bisect.bisect_right(A, a + K) - (i + 1)
    print(ret)
    return


# Generated by 2.13.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    K = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, K, A)

if __name__ == '__main__':
    main()
