#!/usr/bin/env python3
import sys


def solve(N: int, A: "List[int]", B: "List[int]"):
    dp = [100 * N] * N
    dp[0] = 0
    dp[1] = A[0]
    for i in range(2, N):
        dp[i] = min(dp[i - 1] + A[i - 1], dp[i - 2] + B[i - 2])

    print(dp[-1])
    return


# Generated by 2.13.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(N - 2 + 1)]  # type: "List[int]"
    B = [int(next(tokens)) for _ in range(N - 3 + 1)]  # type: "List[int]"
    solve(N, A, B)

if __name__ == '__main__':
    main()
