Bootstrap: localimage
From: ../images/common.simg

%setup
    mkdir -p ${SINGULARITY_ROOTFS}/opt/init/011_aws

%files
    npmrc /usr/local/etc/npmrc
    entry.sh /opt/init/011_aws/entry.sh
    aws_dein.toml /opt/init/011_aws/aws_dein.toml

%labels
    AUTHOR argon.argon.argon@gmail.com

%post
    echo "export SINGULARITY_IMAGE_NAME=aws_$(date +%s)" >> $SINGULARITY_ENVIRONMENT
    echo "export SINGULARITY_XDG_ROOT=\$HOME/.xdg/\$SINGULARITY_IMAGE_NAME" >> $SINGULARITY_ENVIRONMENT
    echo "export XDG_CONFIG_HOME=\$SINGULARITY_XDG_ROOT" >> $SINGULARITY_ENVIRONMENT
    echo "export XDG_CACHE_HOME=\$SINGULARITY_XDG_ROOT" >> $SINGULARITY_ENVIRONMENT
    echo "export XDG_DATA_HOME=\$SINGULARITY_XDG_ROOT" >> $SINGULARITY_ENVIRONMENT
    echo "export XDG_RUNTIME_DIR=\$SINGULARITY_XDG_ROOT" >> $SINGULARITY_ENVIRONMENT

    apt-get update
    apt-get -y install nodejs npm unzip libncurses5 libncurses6
    npm cache verify
    npm install n -g

    n 10.15.3
    ln -sf /usr/local/bin/node /usr/bin/node
    apt-get -y purge nodejs
    apt-get clean

    npm install -g yarn npx create-react-app
    npm install -g typescript typescript-language-server javascript-typescript-langserver 
    npm install -g neovim

    curl -o /tmp/miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
    bash /tmp/miniconda.sh -b -p /opt/miniconda3
    rm  /tmp/miniconda.sh
    /opt/miniconda3/bin/conda install python=3.6
    curl https://bootstrap.pypa.io/get-pip.py -o /tmp/get-pip.py
    /opt/miniconda3/bin/python /tmp/get-pip.py

    /opt/miniconda3/bin/pip install poetry
