[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimfiler.vim'
hook_add = '''
    let g:vimfiler_as_default_explorer = 1
    let g:vimfiler_safe_mode_by_default = 0
    if has('mac')
      let g:vimfiler_quick_look_command = 'qlmanage -p'
    endif
    nnoremap <C-e> :<C-u>VimFilerExplore<CR>
'''

[[plugins]]
repo = 'cespare/vim-toml'
on_ft=['toml']

[[plugins]]
repo = 'Shougo/unite.vim'
depends = ['vimfiler.vim']

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'honza/vim-snippets'

[[plugins]]
repo = 'kana/vim-submode'
hook_post_source = '''
  call submode#enter_with('bufmove', 'n', '', 's>', '<C-w>>')
  call submode#enter_with('bufmove', 'n', '', 's<', '<C-w><')
  call submode#enter_with('bufmove', 'n', '', 's+', '<C-w>+')
  call submode#enter_with('bufmove', 'n', '', 's-', '<C-w>-')
  call submode#map('bufmove', 'n', '', '>', '<C-w>>')
  call submode#map('bufmove', 'n', '', '<', '<C-w><')
  call submode#map('bufmove', 'n', '', '+', '<C-w>+')
  call submode#map('bufmove', 'n', '', '-', '<C-w>-')
'''

[[plugins]]
repo = 'terryma/vim-expand-region'
hook_post_source = '''
  map K <Plug>(expand_region_expand)
  map J <Plug>(expand_region_shrink)
'''

[[plugins]]
repo = 'mileszs/ack.vim'
hook_add = '''
  if executable('ag')
    let g:ackprg = 'ag --vimgrep'
  endif
'''

[[plugins]]
repo = 'morhetz/gruvbox'
hook_source = '''
    color gruvbox
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_source = '''
    let g:ulti_expand_or_jump_res = 0 "default value, just set once
    function! Ulti_ExpandOrJump_and_getRes()
      call UltiSnips#ExpandSnippet()
      return g:ulti_expand_res
    endfunction
    inoremap <C-k> <C-R>=(Ulti_ExpandOrJump_and_getRes() > 0)?"":deoplete#close_popup()<CR>

    let g:deoplete#enable_at_startup = 1
'''
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet.vim'
hook_source = '''
    imap <C-k>     <Plug>(neosnippet_expand_or_jump)
    smap <C-k>     <Plug>(neosnippet_expand_or_jump)
    xmap <C-k>     <Plug>(neosnippet_expand_target)
    " Enable snipMate compatibility feature.
    let g:neosnippet#enable_snipmate_compatibility = 1
    
    " Tell Neosnippet about the other snippets
    let g:neosnippet#snippets_directory="mysnippets"
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
