Bootstrap: library
From: ubuntu:18.10

%runscript
    exec /opt/bin/entry

%setup
    mkdir -p ${SINGULARITY_ROOTFS}/opt/bin
    mkdir -p ${SINGULARITY_ROOTFS}/opt/init/000_common
    chmod -R 777 ${SINGULARITY_ROOTFS}/opt

%files
    entry /opt/bin/entry
    entry.sh /opt/init/000_common/entry.sh
    init.vim /opt/init/000_common/init.vim
    dein.toml /opt/init/000_common/dein.toml
    template /opt/init/000_common/template
    snippets /opt/init/000_common/snippets

%environment
    export ENTRY_COMMAND=bash
    export PATH=/opt/bin:$PATH

%labels
   AUTHOR argon.argon.argon@gmail.com

%post
    echo "export SINGULARITY_IMAGE_NAME=common_$(date +%s)" >> $SINGULARITY_ENVIRONMENT
    echo "export SINGULARITY_XDG_ROOT=\$HOME/.xdg/\$SINGULARITY_IMAGE_NAME" >> $SINGULARITY_ENVIRONMENT
    echo "export XDG_CONFIG_HOME=\$SINGULARITY_XDG_ROOT" >> $SINGULARITY_ENVIRONMENT
    echo "export XDG_CACHE_HOME=\$SINGULARITY_XDG_ROOT" >> $SINGULARITY_ENVIRONMENT
    echo "export XDG_DATA_HOME=\$SINGULARITY_XDG_ROOT" >> $SINGULARITY_ENVIRONMENT
    echo "export XDG_RUNTIME_DIR=\$SINGULARITY_XDG_ROOT" >> $SINGULARITY_ENVIRONMENT
    echo "export DEBIAN_FRONTEND=noninteractive" >> $SINGULARITY_ENVIRONMENT
    echo "export EXERCISM_CONFIG_HOME=\$HOME/.config/exercism" >> $SINGULARITY_ENVIRONMENT
    . $SINGULARITY_ENVIRONMENT

    sed -i '/jessie-updates/d' /etc/apt/sources.list 
    apt-get update -qq
    apt-get install -y git curl software-properties-common language-pack-ja build-essential direnv
    apt-get install -y neovim python-dev python-pip python3-dev python3-pip
    apt-get install -y bash tmux tig unzip httpie jq silversearcher-ag peco
    apt-get install -y dicom3tools dcmtk libgdcm-cil libgdcm-tools imagemagick
    apt-get clean

    curl https://bootstrap.pypa.io/get-pip.py -o /tmp/get-pip.py
    python2 /tmp/get-pip.py -vv
    python3 /tmp/get-pip.py -vv
    rm /tmp/get-pip.py

    pip2 install --upgrade pip
    pip3 install --upgrade pip

    pip2 install --upgrade neovim
    pip3 install --upgrade neovim
    pip3 install xonsh pyt prompt_toolkit pygments

    EXERCISM_CLI_PKG_URL=https://github.com/exercism/cli/releases/download/v3.0.11/exercism-linux-64bit.tgz
    curl -L $EXERCISM_CLI_PKG_URL | tar xz -C /tmp
    mv /tmp/exercism /opt/bin/exercism
