#!/usr/bin/env python3
import sys


def solve(N: int, K: int, L: int, A: "List[int]", B: "List[int]", C: "List[List[int]]"):
    return


# Generated by 2.13.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    K = int(next(tokens))  # type: int
    L = int(next(tokens))  # type: int
    A = [int()] * (K)  # type: "List[int]"
    B = [int()] * (K)  # type: "List[int]"
    for i in range(K):
        A[i] = int(next(tokens))
        B[i] = int(next(tokens))
    C = [[int(next(tokens)) for _ in range(N)] for _ in range(N)]  # type: "List[List[int]]"
    solve(N, K, L, A, B, C)

if __name__ == '__main__':
    main()
