Bootstrap: localimage
From: ../images/common.simg

%setup
    mkdir -p ${SINGULARITY_ROOTFS}/opt/init/010_python

%files
    jupyter-server /opt/bin
    entry.sh /opt/init/010_python/entry.sh
    python_dein.toml /opt/init/010_python/python_dein.toml

%environment
    export PATH=/opt/bin:/opt/miniconda3/bin:$PATH

%labels
    AUTHOR argon.argon.argon@gmail.com

%post
    echo "export SINGULARITY_IMAGE_NAME=python_$(date +%s)" >> $SINGULARITY_ENVIRONMENT
    echo "export SINGULARITY_XDG_ROOT=\$HOME/.xdg/\$SINGULARITY_IMAGE_NAME" >> $SINGULARITY_ENVIRONMENT
    echo "export XDG_CONFIG_HOME=\$SINGULARITY_XDG_ROOT" >> $SINGULARITY_ENVIRONMENT
    echo "export XDG_CACHE_HOME=\$SINGULARITY_XDG_ROOT" >> $SINGULARITY_ENVIRONMENT
    echo "export XDG_DATA_HOME=\$SINGULARITY_XDG_ROOT" >> $SINGULARITY_ENVIRONMENT
    echo "export XDG_RUNTIME_DIR=\$SINGULARITY_XDG_ROOT" >> $SINGULARITY_ENVIRONMENT

    pip3 install poetry
    pip3 install mypy black isort jedi python-language-server pyls-black pyls-isort 
