Bootstrap: localimage

From: ../images/dev_env.simg


%runscript

    exec /opt/miniconda3/bin/python

%setup

%files
   
    python_dein.toml /opt/nvim/specs

%environment

    PATH=/opt/miniconda3/bin:$PATH
    PYTHONPATH=/opt/miniconda3/lib/python3.7/site-packages:$PYTHONPATH

    export PATH PYTHONPATH

%labels

%post

    export XDG_CONFIG_HOME=/opt/
    export XDG_DATA_HOME=/opt/

    curl -o /tmp/miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
    bash /tmp/miniconda.sh -b -p /opt/miniconda3
    rm  /tmp/miniconda.sh

    /opt/miniconda3/bin/conda install -y jupyter
    /opt/miniconda3/bin/conda install -y -c r libiconv
    /opt/miniconda3/bin/conda install -y -c conda-forge gdcm pydicom nibabel
    /opt/miniconda3/bin/conda install -y -c simpleitk simpleitk
    /opt/miniconda3/bin/conda install -y tensorflow
    /opt/miniconda3/bin/conda install -y -c conda-forge xgboost lightgbm
    /opt/miniconda3/bin/conda install -y -c conda-forge numpy scipy scikit-learn scikit-image matplotlib seaborn bokeh holoviews pillow networkx
    /opt/miniconda3/bin/conda install -y -c conda-forge pandas pandas-datareader
    /opt/miniconda3/bin/conda install -y -c conda-forge flask tinydb scrapy requests hy click
    /opt/miniconda3/bin/conda install -y -c conda-forge black jedi pytest pytest-xdist python-language-server
    /opt/miniconda3/bin/conda install -y -c conda-forge dash dash-renderer dash-html-components dash-core-components plotly
    /opt/miniconda3/bin/conda install -y cython
    /opt/miniconda3/bin/conda clean -t
    /opt/miniconda3/bin/pip install pyenv pipenv

    nvim -c 'call dein#install()' -c 'q'
    nvim -c 'UpdateRemotePlugins' -c 'q'
    chmod -R 777 /opt/nvim/shada
