[package]
name = "rust"
version = "0.1.0"
authors = ["Masahiro Wada <argon.argon.argon@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.36"
itertools = "0.9.0"
