[[plugins]]
repo = 'Rip-Rip/clang_complete'
hook_source = '''
    let g:clang_library_path='/usr/lib/x86_64-linux-gnu/libclang-4.0.so'
'''
on_ft=['cpp','c']

[[plugins]]
repo = 'lyuts/vim-rtags'
on_ft=['cpp','c']
