#!/usr/bin/env python3
import sys


def solve(N: int, S: str):
    ws = 0
    es = 0
    for s in S:
        ws += int(s == 'W')
        es += int(s == 'E')

    ce = 0
    cw = 0
    ret = N
    for s in S:
        ce += int(s == 'E')
        ret = min(ret, cw + (es - ce), )
        cw += int(s == 'W')
    print(ret)




# Generated by 1.1.4 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    S = next(tokens)  # type: str
    solve(N, S)

if __name__ == '__main__':
    main()
