version: '3'
services:
  dev:
    image: mcr.microsoft.com/devcontainers/base:ubuntu24.04
    depends_on:
      - neo4j
    container_name: dev_container
    volumes:
      - ..:/workspace
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=neo4jpassword
    tty: true
    #command: sleep infinity

  neo4j:
    image: neo4j:latest
    container_name: neo4j_container
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt
    environment:
      - NEO4J_AUTH=neo4j/neo4jpassword
      - NEO4JLABS_PLUGINS=["apoc", "graph-data-science"]
    volumes:
      - ../neo4j/data:/data
      - ../neo4j/logs:/logs
      - ../neo4j/import:/var/lib/neo4j/import
      - ../neo4j/plugins:/plugins