#!/usr/bin/env python3
import sys

YES = "Yes"  # type: str
NO = "No"  # type: str


# Generated by 2.13.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    N, Q = map(int, input().split())

    par = [i for i in range(N + 1)]
    siz = [1 for _ in range(N + 1)]

    def root(x):
        while x != par[x]:
            x = par[x]
        return x

    def unite(u, v):
        root_u = root(u)
        root_v = root(v)
        if root_u == root_v:
            return
    
        if siz[root_u] < siz[root_v]:
            par[root_u] = root_v
            siz[root_v] += siz[root_u]
        else:
            par[root_v] = root_u
            siz[root_u] += siz[root_v]

    def same(u, v):
        return root(u) == root(v)

    while l := sys.stdin.readline():
        q, u, v = map(int, l.split())
        if q == 1:
            unite(u, v)
        else:
            if same(u, v):
                print(YES)
            else:
                print(NO)
    return

if __name__ == '__main__':
    main()
