#!/usr/bin/env sh

_DOCKER=${DOCKER_CMD:-'docker'}
_PWD=`pwd`
_USER=`whoami`
_DATE=`date +"%Y-%m-%d %R:%S"`
_IMAGE=$1

RUN_ARGS=""
if [ -t 0 ] ; then
    RUN_ARGS="-i $RUN_ARGS"
fi
if [ -t 1 ] ; then
    RUN_ARGS="-t $RUN_ARGS"
fi

PORT_ARGS=""
IFS=,
for PORT_MAP in $RUN_IN_PORT_MAPS
do
    PORT_ARGS="$PORT_ARGS -p $PORT_MAP"
done
unset IFS

NET_ARG=""
if [ -n "$RUN_IN_NETWORK" ] ; then
    NET_ARG=" --net $RUN_IN_NETWORK"
fi

shift
#docker run -it --rm -u $_USER -w $_PWD -v $HOME:/home/$_USER $_IMAGE faketime "$_DATE" $@
docker run $RUN_ARGS --rm -u $_USER -w $_PWD -v $HOME:/home/$_USER $PORT_ARGS $NET_ARG $_IMAGE $@
