#!/usr/bin/env sh

_DOCKER=${DOCKER_CMD:-'docker'}
_PWD=`pwd`
_USER=`whoami`
_DATE=`date +"%Y-%m-%d %R:%S"`
_IMAGE=$1

RUN_ARGS=""
if [ -t 0 ] ; then
    RUN_ARGS="-i $RUN_ARGS"
fi
if [ -t 1 ] ; then
    RUN_ARGS="-t $RUN_ARGS"
fi

shift
#docker run -it --rm -u $_USER -w $_PWD -v $HOME:/home/$_USER $_IMAGE faketime "$_DATE" $@
docker run $RUN_ARGS --rm -u $_USER -w $_PWD -v $HOME:/home/$_USER $_IMAGE $@
