[tool.poetry]
name = "openvino_yolo_study"
version = "0.1.0"
description = ""
authors = ["Masahiro Wada <argon.argon.argon@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
numpy = "^1.16"
tensorflow = "=1.5.0"
pillow = "^6.1"
requests = "^2.22"
networkx = "^2.3"
test-generator = "^0.1.2"
defusedxml = "^0.6.0"

[tool.poetry.dev-dependencies]
pudb = "^2019.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
