#!/usr/bin/env python3
import sys


def solve(X: int):
    v = [1]
    for i in range(2, X + 1):
        sq = i
        while True:
            sq *= i
            if X < sq:
                break
            v.append(sq)
    print(sorted(v)[-1])


# Generated by 1.1.4 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    X = int(next(tokens))  # type: int
    solve(X)

if __name__ == '__main__':
    main()
