#!/usr/bin/env python3
import sys


def solve(N: int, L: int, A: "List[int]", B: "List[str]"):
    return


# Generated by 2.13.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    L = int(next(tokens))  # type: int
    A = [int()] * (N)  # type: "List[int]"
    B = [str()] * (N)  # type: "List[str]"
    for i in range(N):
        A[i] = int(next(tokens))
        B[i] = next(tokens)
    solve(N, L, A, B)

if __name__ == '__main__':
    main()
