service: quotebot-line

provider:
  name: aws
  runtime: nodejs4.3

functions:
  webhook:
    handler: handler.webhook
    events:
      - http:
          method: POST
          path: webhook
          integration: lambda
