#!/usr/bin/env python
# -*- coding:utf-8 -*-

import itertools
import collections

def is_prime( p ):
    if p < 2:
        return False

    i = 2;
    while i * i <= p:
        if p % i == 0:
            return False
        i += 1
    return True

def main():
    for c in itertools.combinations( '0123456789', 4 ):
        res = []
        for p in itertools.permutations( ''.join( c ), 4 ):
            print( prime )
            prime = int( ''.join( p ) )
            if prime < 1000:
                continue


            if is_prime( prime ):
                res.append( prime )

        if 3 <= len( res ):
            dic = collections.defaultdict( set )
            for i,x in enumerate( res ):
                for y in res[ i + 1: ]:
                    diff = abs( y - x )
                    dic[ diff ].add( (x,y) )
            for diff, vs in  dic.items():
                if len( vs ) == 2:
                    x1, x2 = vs.pop()
                    x3, x4 = vs.pop()
                    xx = sorted( [ x1, x2, x3, x4 ] )
                    if xx[ 1 ] == xx[ 2 ]:
                        print( diff, xx[ 0 ], xx[ 1 ], xx[ 3 ] )

    return

if __name__ == '__main__':
    main()
