#!/usr/bin/env python3
import sys
import itertools


def solve(N: int, A: "List[int]", D: int, L: "List[int]", R: "List[int]"):
    accf = [0] + list(itertools.accumulate(A, max))
    accr = [0] + list(itertools.accumulate(reversed(A), max))

    for l, r in zip(L, R):
        print(max(accf[l-1], accr[N - r]))

    return


# Generated by 2.13.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    D = int(next(tokens))  # type: int
    L = [int()] * (D)  # type: "List[int]"
    R = [int()] * (D)  # type: "List[int]"
    for i in range(D):
        L[i] = int(next(tokens))
        R[i] = int(next(tokens))
    solve(N, A, D, L, R)

if __name__ == '__main__':
    main()
