Bootstrap: docker

From: ubuntu:latest


%runscript

   exec bash

%setup

    mkdir -p ${SINGULARITY_ROOTFS}/opt/nvim/specs
    mkdir ${SINGULARITY_ROOTFS}/opt/bin
    chmod -R 777 ${SINGULARITY_ROOTFS}/opt

%files

    init.vim /opt/nvim/init.vim
    dein.toml /opt/nvim/dein.toml
    template /opt/nvim/template

%environment

    export XDG_CONFIG_HOME=/opt/
    export XDG_DATA_HOME=/opt/
    export XDG_RUNTIME_DIR=$HOME/.local/share
    export PATH=/opt/bin:$PATH

%labels

   AUTHOR argon.argon.argon@gmail.com

%post

    export XDG_CONFIG_HOME=/opt/
    export XDG_DATA_HOME=/opt/

    apt-get update -qq
    apt-get upgrade -qq
    apt-get install -y software-properties-common language-pack-ja build-essential
    apt-get install -y git curl

    add-apt-repository ppa:neovim-ppa/unstable
    apt-get update
    apt-get -y install neovim python-dev python-pip python3-dev python3-pip

    pip2 install --upgrade pip neovim
    pip3 install --upgrade pip neovim
    nvim -c 'call dein#install()' -c 'q'
    nvim -c 'UpdateRemotePlugins' -c 'q'
    chmod -R 777 /opt/nvim/shada

    apt-get clean
