#!/usr/bin/env python3
import sys


def solve(T: int, P: "List[int]", Q: "List[int]", R: "List[int]"):
    return


# Generated by 2.13.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    T = int(next(tokens))  # type: int
    P = [int()] * (T)  # type: "List[int]"
    Q = [int()] * (T)  # type: "List[int]"
    R = [int()] * (T)  # type: "List[int]"
    for i in range(T):
        P[i] = int(next(tokens))
        Q[i] = int(next(tokens))
        R[i] = int(next(tokens))
    solve(T, P, Q, R)

if __name__ == '__main__':
    main()
