Bootstrap: localimage
From: ../images/common.simg

%setup
    mkdir -p ${SINGULARITY_ROOTFS}/opt/init/011_node

%files
    npmrc /usr/local/etc/npmrc
    entry.sh /opt/init/011_node/entry.sh
    node_dein.toml /opt/init/011_node/node_dein.toml

%labels
    AUTHOR argon.argon.argon@gmail.com

%post
    echo "export SINGULARITY_IMAGE_NAME=node_$(date +%s)" >> $SINGULARITY_ENVIRONMENT
    echo "export SINGULARITY_XDG_ROOT=\$HOME/.xdg/\$SINGULARITY_IMAGE_NAME" >> $SINGULARITY_ENVIRONMENT
    echo "export XDG_CONFIG_HOME=\$SINGULARITY_XDG_ROOT" >> $SINGULARITY_ENVIRONMENT
    echo "export XDG_DATA_HOME=\$SINGULARITY_XDG_ROOT" >> $SINGULARITY_ENVIRONMENT
    echo "export XDG_RUNTIME_DIR=\$SINGULARITY_XDG_ROOT" >> $SINGULARITY_ENVIRONMENT

    apt-get update
    apt-get -y install nodejs npm unzip
    npm cache verify
    npm install n -g

    n latest
    ln -sf /usr/local/bin/node /usr/bin/node
    apt-get -y purge nodejs
    apt-get clean

    npm install webpack webpack-dev-server yarn -g
    npm install bs-platform -g
    npm install reason-cli@latest-linux -g
    npm install ocaml-language-server -g
