Bootstrap: localimage

From: ../images/dev_env.simg


%runscript

    exec /usr/local/bin/node

%setup

%files

    npmrc /usr/local/etc/npmrc
    node_dein.toml /opt/nvim/specs

%environment


%labels

%post

    export XDG_CONFIG_HOME=/opt/
    export XDG_DATA_HOME=/opt/

    apt-get update
    apt-get -y install nodejs npm unzip
    npm cache clean
    npm install n -g

    n latest
    ln -sf /usr/local/bin/node /usr/bin/node
    apt-get -y purge nodejs
    apt-get clean

    npm install webpack webpack-dev-server yarn -g
    npm install bs-platform -g
    npm install reason-cli@latest-linux -g
    npm install ocaml-language-server -g

    nvim -c 'call dein#install()' -c 'q'
    nvim -c 'UpdateRemotePlugins' -c 'q'
    chmod -R 777 /opt/nvim/shada
