on:
  push:
    branches:
      - quarto
  workflow_dispatch:

name: Quarto Publish

jobs:     
  build-site:
    runs-on: ubuntu-latest
      
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Jupyter
        run: pip install jupyter

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.4.554

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          render: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
