name: publish
on:
  push:
    branches:
      - quarto
  workflow_dispatch:

jobs:     
  build-site:
    if: ( github.event.commits[0].message != 'Initial commit' ) || github.run_number > 1
    runs-on: ubuntu-latest
    steps:
      
    - name: Copy Repository Contents
      uses: actions/checkout@main
      with:
        persist-credentials: false

    - name: Setup quarto
      run: |
        curl -L -o quarto.deb "https://github.com/quarto-dev/quarto-cli/releases/download/v${QUARTO_VERSION}/quarto-${QUARTO_VERSION}-linux-amd64.deb"
        dpkg -i quarto.deb
      env:
        QUARTO_VERSION: "1.2.218"
    - name: Publish
      run: |
        echo "GITHUB_TOKEN=${GITHUB_TOKEN}" > _environment
        quarto publish gh-pages --no-prompt --no-browser
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
