#!/usr/bin/env python3
import sys


def solve(N: int, C: "List[str]"):
    return


# Generated by 2.13.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    C = [next(tokens) for _ in range(N)]  # type: "List[str]"
    solve(N, C)

if __name__ == '__main__':
    main()
